from enum import StrEnum


class Lang(StrEnum):
    ENGLISH = "english"
    SPANISH = "spanish"
    FRENCH = "french"
    GERMAN = "german"
    ITALIAN = "italian"
    PORTUGUESE = "portuguese"
    RUSSIAN = "russian"
    JAPANESE = "japanese"
    KOREAN = "korean"
    CHINESE = "chinese"
    ARABIC = "arabic"
    HINDI = "hindi"
    TURKISH = "turkish"
    POLISH = "polish"
    DUTCH = "dutch"
    NORWEGIAN = "norwegian"
    SWEDISH = "swedish"
    DANISH = "danish"
    FINNISH = "finnish"
    CZECH = "czech"
    ROMANIAN = "romanian"
    GREEK = "greek"
    HUNGARIAN = "hungarian"
    SLOVAK = "slovak"
    BULGARIAN = "bulgarian"
    CROATIAN = "croatian"
    LITHUANIAN = "lithuanian"
    SLOVENIAN = "slovenian"
    ESTONIAN = "estonian"
    LATVIAN = "latvian"
    VIETNAMESE = "vietnamese"
    THAI = "thai"
    INDONESIAN = "indonesian"
    MALAY = "malay"
    CATALAN = "catalan"
    IRISH = "irish"
