[default] # APP_ENV='local'

# Business Details
BUSINESS_NAME = 'Your Company Name'
BUSINESS_ADDRESS = 'Your Address'

# Backend
PROJECT_NAME = 'scaffold'
API_V1_STR = '/api/v1'
SECRET_KEY = '3d26aa1085857dded2e6ea2daa73edd103976d8f064df1a172b1806e1edc2abc'
BACKEND_CORS_ORIGINS = [
    "http://localhost",
    "http://localhost:3000",
    "https://localhost",
    "https://localhost:3000",
]
SITE_HOST='localhost:3000'
SERVER_HOST = 'localhost:8123'
HTTPS_SITE = false
HTTPS_SERVER = false
JSON_LOGS = false
USERS_OPEN_REGISTRATION = true
AUTH_FLOW = 'oauth2'
AUTH_JWKS_TTL_MINS = 120

# Admin
FIRST_SUPERUSER = 'admin@example.com'

# Test
TEST_USER = "testuser@example.com"

# Email
EMAILS_ENABLED = false
SMTP_TLS = true
SMTP_PORT = 587
SMTP_HOST = "smtp.sendgrid.net"
SMTP_USER = "apikey"
# SMTP_PASSWORD=
EMAILS_FROM_EMAIL = 'no-reply@example.com'
SUPPORT_EMAIL = 'support@example.com'

# Postgres
POSTGRES_USER = 'admin'
POSTGRES_PASSWORD = 'admin_pass'
POSTGRES_DB = 'scaffold_db'

# Redis
REDIS_PASSWORD = 'local_redis_pass'
REDIS_DB = 0

[host] # APP_ENV='local:host'
POSTGRES_HOST = 'localhost'
POSTGRES_PORT = 7777
REDIS_HOST = 'localhost'
REDIS_PORT = 6377

[docker] # APP_ENV='local:docker'
POSTGRES_HOST = 'scaffold_postgres'
POSTGRES_PORT = 5432
REDIS_HOST = 'scaffold_redis'
REDIS_PORT = 6379
